AWSTemplateFormatVersion: 2010-09-09
Description: Hello Lambda
Metadata: 

Parameters: 

Mappings: 

Conditions: 

Resources:
  hello-lambda: 
  Type: "AWS::Lambda::Function"
  Properties: 
    Handler: "index.handler"
    Role: 
      Fn::GetAtt: 
        - "LambdaExecutionRole"
        - "Arn"
    Code: 
      S3Bucket: "lambda-functions"
      S3Key: "amilookup.zip"
    Runtime: "nodejs10.x"
    Timeout: 25
    TracingConfig:
      Mode: "Active"

Outputs: